version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=challenge
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/database/data
      - ./migrate.sql:/docker-entrypoint-initdb.d/migrate.sql

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment: 
      - NODE_ENV=development
      - LOGGER=true
      - LOG_LEVEL=debug
      - DEBUG_MODE=false
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend